In [1]:
import cv2
import numpy as np
import os
import time
import scipy.io as sio
import matplotlib.pyplot as plt
import math
import main_functions as main

In [2]:
if __name__ == '__main__':
    main.main_slp_linear()
    

[5 2 3 ... 2 9 8]
(10, 10)
(10, 10) (1, 196)


ValueError: cannot reshape array of size 19600 into shape (1,1960)

In [78]:
a = np.array([1,2,-1,1])
b = np.flip(a)
#p = np.where(a > 5,1,0)
k = np.convolve(a,a)
print(k,b)
c = 4
np.ceil(c)

[ 1  4  2 -2  5 -2  1] [ 1 -1  2  1]


4.0

In [5]:
def im2col_sliding_strided(A, BSZ, stepsize=1):
    # Parameters
    m,n = A.shape
    s0, s1 = A.strides    
    nrows = m-BSZ[0]+1
    ncols = n-BSZ[1]+1
    shp = BSZ[0],BSZ[1],nrows,ncols
    strd = s0,s1,s0,s1

    out_view = np.lib.stride_tricks.as_strided(A, shape=shp, strides=strd)
    return out_view.reshape(BSZ[0]*BSZ[1],-1)[:,::stepsize]

In [97]:
A = np.arange(4**2).reshape((4,4))
B = np.pad(A, (0, 0), 'constant', constant_values=0)
D = np.pad(A, ((0,0), (0,1)), 'constant', constant_values=0)
print(A)
#print(B)
#print(D)
BSZ = (2,2)

C = im2col_sliding_strided(B, BSZ, 2)
#print(C)
#print(np.rot90(np.rot90(A)).reshape((1,np.size(A)) ))
      
#print(np.flip(A.reshape((1,np.size(A)) )  ))
#print(np.max(C,axis = 0))




M, N = A.shape
K = 2
L = 2

MK = M // K
NL = N // L

print(A[:MK*K, :NL*L].reshape(MK, K, NL, L).max(axis=(1, 3)))

#print(A[:MK*K, :NL*L].reshape(MK, K, NL, L))

E = A[:MK*K, :NL*L].reshape(MK, K, NL, L)

for i in range(MK):
    for j in range(NL):
        print(E[i,:,j,:],np.max(E[i,:,j,:]))
        
        E[i,:,j,:] = np.where( E[i,:,j,:] == np.max(E[i,:,j,:]),1,0)
        
        print(E[i,:,j,:])
print(E.reshape([M,N]))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5  7]
 [13 15]]
[[0 1]
 [4 5]] 5
[[0 0]
 [0 1]]
[[2 3]
 [6 7]] 7
[[0 0]
 [0 1]]
[[ 8  9]
 [12 13]] 13
[[0 0]
 [0 1]]
[[10 11]
 [14 15]] 15
[[0 0]
 [0 1]]
[[0 0 0 0]
 [0 1 0 1]
 [0 0 0 0]
 [0 1 0 1]]


In [8]:
k = np.random.rand(3,3)
a = np.array([2.7,1,3])
c = np.array([4,9,7])
b = a.reshape([3,1])
#print(k@a,k@b)
d = np.outer(a,c)
#print(np.linalg.norm(a-c,2)**2,np.sum((a-c)**2))
print(k,k[1,:])

l =[]
for i in range(8):
    l.append(k)
len(l)
l[1].shape
a = np.array(l[1]).reshape((1,9))


[[0.01275815 0.98735194 0.48331107]
 [0.73951974 0.09412153 0.96166489]
 [0.79312298 0.17502292 0.09582755]] [0.73951974 0.09412153 0.96166489]


In [128]:
def get_mini_batch(im_train, label_train, batch_size):
    # TO DO
    
    image_vec, n_train = im_train.shape   #Decompose the im
    
    batch_perm = np.random.permutation(n_train)
    
    n_batch = np.int(n_train//batch_size)
    
    mini_batch_x = []
    mini_batch_y = []
    
    for i in range(n_batch):
        
        end_id = np.min([i*batch_size+batch_size,n_train])
        id_x =batch_perm[np.arange(i*batch_size,end_id,1)]
        
        mini_batch_x.append(im_train[:, id_x])
        
        num_class = 10
        targets = np.array([label_train[id_x]]).reshape(-1)
        one_hot_targets = np.eye(num_class)[targets]
        
        mini_batch_y.append(one_hot_targets)
    
    return mini_batch_x, mini_batch_y

In [129]:
def fc(x, w, b):
    # TO DO
    # w:batch*196    # x:196*1    # b:batch*1
    
    y = w @ x+b
        
    return y

In [130]:
def fc_backward(dl_dy, x, w, b, y):
    # TO DO
    dl_dx = w.T @ dl_dy  # 196 * batch
    
    dl_dw = np.outer(dl_dy , x).reshape((1,np.size(w)))
    
    dl_db = dl_dy
    
    return dl_dx, dl_dw, dl_db

In [131]:
def loss_euclidean(y_tilde, y):
    # TO DO
    l = np.linalg.norm((y_tilde-y),2)**2
    dldy = 2 * (y_tilde - y)
    
    return l, dl_dy

In [132]:
def loss_cross_entropy_softmax(x, y):
    # TO DO
    x_tilde = np.exp(x)
    
    x_sum = np.sum(x_tilde)
    
    y_tilde = x_tilde / x_sum
    
    L = - np.sum(y * np.log(y_tilde) )
    
    dl_dy = y_tilde - y
    
    return l, dl_dy

In [133]:
def relu(x):
    # TO DO
    return y

In [134]:
def relu_backward(dl_dy, x, y):
    # TO DO
    return dl_dx

In [135]:
def conv(x, w_conv, b_conv):
    # TO DO
    return y


In [136]:
def conv_backward(dl_dy, x, w_conv, b_conv, y):
    # TO DO
    return dl_dw, dl_db

In [137]:
def pool2x2(x):
    # TO DO
    return y

In [138]:
def pool2x2_backward(dl_dy, x, y):
    # TO DO
    return dl_dx

In [139]:
def flattening(x):
    # TO DO
    return y

In [140]:
def flattening_backward(dl_dy, x, y):
    # TO DO
    return dl_dx

In [141]:
def train_slp_linear(mini_batch_x, mini_batch_y):
    # TO DO
    
    # learning rate
    gamma = 0.0001
    
    # decay rate
    lamda = 0.985

    # init weight
    w = np.random.rand(10,196)
    b =  np.random.rand(10, 1)

    # number of iteration
    n_Iter = 2000

    # number of minibatch
    nBatch = len(mini_batch_x)
    #batchSize = 30;

    # cell to matrix
    #mini_x = zeros(nBatch, 196, batchSize);
    #mini_y = zeros(nBatch, 10, batchSize);
    
    #for i= 1: nBatch
        #mini_x(i,:, :) = mini_batch_x{i,1};
        #mini_y(i, :, :) = mini_batch_y{i,1};
    
    #loss_curve = []

    for id_x in range(nIter):
        if ((id_x % 10) == 0):
            gamma = gamma * lamda
            
        dLdw = np.zeros((1,np.size(w)))
        dLdb = np.zeros_like(b)
        for i in range(nBatch):
            L = 0
            batch_size = len(mini_batch_x[i])
            
            for j in range(batch_size):
                x = ((mini_batch_x[i])[j,:]).reshape((1,196))
                y_tilde = fc(x, w, b);
                y = ((mini_batch_y[i])[j,:]).reshape((1,10))
                
                # loss
                loss, dldy = Loss_euclidean(y_tilde, y) 
                
                # dldy -- n*1
                dldx, dldw, dldb = FC_backward(dldy, x, w, b, y)
                dLdw = dLdw + dldw.reshape((10, 196))
                dLdb = dLdb + dldb
                L = L + loss
        
            w = w - gamma/batchSize*dLdw;
            b = b - gamma/batchSize*dLdb;
            L = L / batchSize;
       
    return w, b

In [142]:
def train_slp(mini_batch_x, mini_batch_y):
    # TO DO
    return w, b

In [143]:
def train_mlp(mini_batch_x, mini_batch_y):
    # TO DO
    return w1, b1, w2, b2

In [144]:
def train_cnn(mini_batch_x, mini_batch_y):
    # TO DO
    return w_conv, b_conv, w_fc, b_fc

In [5]:
if __name__ == '__main__':
    main.main_slp_linear()
    

IndexError: index 11445 is out of bounds for axis 0 with size 1

In [146]:
    main.main_slp()
    main.main_mlp()
    main.main_cnn()

NameError: name 'mini_batch_x' is not defined