In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [14]:
def get_differential_filter(im):
    # To do
    kernel_x = np.tile(np.array([1,0,-1]),(3,1))
    kernel_y = np.tile(np.vstack(np.array([1,0,-1])),3)
    im = im.astype('float') / 255.0
    
    
    return filter_x, filter_y

In [ ]:
im = cv2.imread('einstein.jpg', 0)
get_differential_filter(im)

In [44]:
im = cv2.imread('einstein.jpg', 0)
kernel_x = np.tile(np.array([1,0,-1]),(3,1))
kernel_y = np.tile(np.vstack(np.array([1,0,-1])),3)
im = im.astype('float') / 255.0
im_zero_pad = np.pad(im, ((1,1),(1,1)), 'constant')
print(kernel_y)
filter_x = np.zeros(im.shape)
filter_y = np.zeros(im.shape)

height,width = im_zero_pad.shape


for i in range(1,height-1,1):
    for j in range(1,width-1,1):
        cell = np.array([[im_zero_pad[i-1,j-1],im_zero_pad[i-1,j],im_zero_pad[i-1,j+1]],
                        [im_zero_pad[i,j-1],im_zero_pad[i,j],im_zero_pad[i,j+1]],
                        [im_zero_pad[i+1,j-1],im_zero_pad[i+1,j],im_zero_pad[i+1,j+1]]])
        filter_x[i-1,j-1] = np.corrcoef(cell.reshape(``),kernel_x)
        filter_y[i-1,j-1] = np.corrcoef(cell,kernel_y)

[[ 1  1  1]
 [ 0  0  0]
 [-1 -1 -1]]


F:\AppStore\Anaconda\lib\site-packages\numpy\lib\function_base.py:3183: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
F:\AppStore\Anaconda\lib\site-packages\numpy\lib\function_base.py:3184: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


ValueError: setting an array element with a sequence.

In [43]:
print(cell)
a = np.array([1,2,3,4,5,6,7])
a[1:4]

[[0.2745098  0.27058824 0.        ]
 [0.2745098  0.2627451  0.        ]
 [0.         0.         0.        ]]


array([2, 3, 4])