In [11]:
import numpy as np
a = [0,1,5,3,1,7,2,6,4,9,10,2,4,5,6,5,7]
b = [0,1,5,5,3,7,2,6,4,9,2,2,5,5,7,5,4]
m_a = np.max([a,b])+1

print(m_a)

11


In [12]:
out = np.zeros((m_a ,m_a))
for i in range(len(a)):
    out[a[i],b[i]]= out[a[i],b[i]] + 1
    
print(out)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
