In [178]:
import numpy as np
from scipy import signal
import math

In [179]:
A =np.array([[1,2,3],[2,3,4]])
#print(np.sum(A))
A.shape

(2, 3)

In [180]:
a,b,c = A[:,]

ValueError: not enough values to unpack (expected 3, got 2)

In [181]:
print(np.floor(2.3) ,np.ceil(2.3) )

2.0 3.0


In [193]:
p = np.array([[1,1,1],[5,5,5],[25,25,25]])
print(p)
np.diff(p,axis=0,n=2)

[[ 1  1  1]
 [ 5  5  5]
 [25 25 25]]


array([[16, 16, 16]])

In [194]:
K = np.concatenate((p,p))

In [206]:
KK = K.reshape((2,3,3))
print(KK)

[[[ 1  1  1]
  [ 5  5  5]
  [25 25 25]]

 [[ 1  1  1]
  [ 5  5  5]
  [25 25 25]]]


In [210]:
LL = np.argwhere(KK == np.ones((1,3)))
print(LL)

[[0 0 0]
 [0 0 1]
 [0 0 2]
 [1 0 0]
 [1 0 1]
 [1 0 2]]


In [190]:
B = np.array([1,2,3])

In [70]:
C = np.matlib.repmat(B, 1, 3)
print(C)

[[1 2 3 1 2 3 1 2 3]]


In [71]:
D = C.reshape((1,len(B),3))
print(D)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]]


In [74]:
F = D[:,:,0]
print(F)

[[1 1 1]]


In [38]:
l = np.ones((1,2))

In [37]:
Q = np.ones((3,3))
~Q

TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [142]:
math.atan(1/2.6)
l = np.array([1,2,3])

In [143]:
print(A)
m = np.matlib.repmat(A, 3, 1).T
print(m)
m = m.reshape((A.shape[0],A.shape[1],3))
print(m[:,:,0])

[[1 2 3]
 [2 3 4]]
[[1 2 1 2 1 2]
 [2 3 2 3 2 3]
 [3 4 3 4 3 4]]
[[1 2 2]
 [3 3 4]]


In [146]:
print(A)
p = np.kron(np.ones((1,3)), A)
m = p.reshape((A.shape[0],A.shape[1],3))
print(m[:,:,0])

[[1 2 3]
 [2 3 4]]
[[1. 1. 1.]
 [2. 2. 2.]]


In [156]:

print(A)
temp_1 = A.reshape((A.shape[0],A.shape[1],1))
p = np.tile(temp_1,(1,1,3))
#m = p.reshape((A.shape[0],A.shape[1],3))
print(m[:,:,0])

[[1 2 3]
 [2 3 4]]
[[1 2 3]
 [2 3 4]]


In [158]:
np.where(A==2,-5,A)

array([[ 1, -5,  3],
       [-5,  3,  4]])

In [159]:
np.any(A==2)

True

In [161]:
np.zeros((1,2))

array([[0., 0.]])

In [165]:
hp_sze = 3
x = 5
y = 5
a = np.zeros((10,10))
a[y - hp_size : y + hp_size + 1, x - hp_size : x + hp_size + 1].shape

(7, 7)

In [167]:
b = 1
b += 1
print(b)

2


In [170]:
np.argwhere(A!=0)

array([[0, 0],
       [0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2]], dtype=int64)

In [175]:
v = np.flip(A.argsort(axis=1))
print(v)

[[2 1 0]
 [2 1 0]]


In [177]:
p[v]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [215]:
loc = np.load('./test/blocks.npy')

ValueError: Object arrays cannot be loaded when allow_pickle=False