In [1]:
import numpy as np
from scipy import signal

In [3]:
A =np.array([[1,2,3],[2,3,4]])
print(np.sum(A))

15


In [4]:
a,b,c = A[:,]

In [17]:
print(np.floor(2.3) ,np.ceil(2.3) )

2.0 3.0


In [19]:
p = np.array([[1,1,1],[5,5,5],[25,25,25]])
print(p)
np.diff(p,axis=0,n=2)

[[ 1  1  1]
 [ 5  5  5]
 [25 25 25]]


array([[16, 16, 16]])

In [23]:
np.concatenate((A,A))

array([[1, 2, 3],
       [2, 3, 4],
       [1, 2, 3],
       [2, 3, 4]])

In [26]:
np.ones((2,1))

array([[1.],
       [1.]])

In [28]:
np.min(A)

1

In [30]:
np.atan(4)

AttributeError: module 'numpy' has no attribute 'atan'